### ISSUE TITLE
SSO support

### ISSUE THREAD

**Issue by matseitz-cisco** [RallyTools/Rally-User-Management#24]
How may I use these scripts in a Workspace that is configured for Single Sign-On support?

**Comment by cktech529** [comment]
I second this question.

Also, when I try to use these using the sandbox I get:

C:\repos\Rally-User-Management>ruby user_permissions_summary.rb
Connecting to Rally: https://sandbox.rallydev.com/slm as christopher.king@emc.com...
Running initial query of users...
Found a total of 3537 Enabled Users.
Summarizing users and writing permission summary output file...
C:/repos/Rally-User-Management/lib/go_user_permissions_summary.rb:223:in `block (2 levels) in go_user_permissions_summary'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rally_api-1.2.1/lib/rally_api/rally_collection.rb:36:in `each'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rally_api-1.2.1/lib/rally_api/rally_collection.rb:36:in `each'
C:/repos/Rally-User-Management/lib/go_user_permissions_summary.rb:200:in `block in go_user_permissions_summary'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rally_api-1.2.1/lib/rally_api/rally_query_result.rb:22:in `block in each'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rally_api-1.2.1/lib/rally_api/rally_query_result.rb:21:in `each'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rally_api-1.2.1/lib/rally_api/rally_query_result.rb:21:in `each'
C:/repos/Rally-User-Management/lib/go_user_permissions_summary.rb:179:in `go_user_permissions_summary'
user_permissions_summary.rb:38:in `<main>'
undefined method `[]' for nil:NilClass

If I try rally_api 1.0.1 I get:

C:\repos\Rally-User-Management>ruby user_permissions_summary.rb
Connecting to Rally: https://sandbox.rallydev.com/slm as christopher.king@emc.com...
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rally_api-1.0.1/lib/rally_api/rally_json_connection.rb:142:in `rescue in send_request'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rally_api-1.0.1/lib/rally_api/rally_json_connection.rb:136:in `send_request'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rally_api-1.0.1/lib/rally_api/rally_json_connection.rb:61:in `setup_security_token'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rally_api-1.0.1/lib/rally_api/rally_rest_json.rb:82:in `initialize'
C:/repos/Rally-User-Management/lib/go_user_permissions_summary.rb:130:in `new'
C:/repos/Rally-User-Management/lib/go_user_permissions_summary.rb:130:in `go_user_permissions_summary'
user_permissions_summary.rb:38:in `<main>'
RallyAPI: - rescued exception - SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: sslv3 alert handshake failure on request to https://sandbox.rallydev.com/slm/webservice/v2
.0/security/authorize.js with params {}

**Comment by jpkole** [comment]
From web page:
    https://help.rallydev.com/technical-overview-implementing-single-sign-on

    Note: This service is only available for customers with active production subscriptions.
               Free, Sandbox and Trial subscriptions are not eligible for this service.

**Comment by cktech529** [comment]
Thanks, 

Yeah we have an active subscription; however, the Sandbox is using USER/PWD, Production is using SSO. 
The idea was to use the SANDBOX to do testing (to avoid causing issues with Production)

Also, it turns out APIKeys are not supported in the sandbox environment either. 

I need to be able to take a bulk list of active users from WORKSPACE A, and grand them WorkspacePermission to WORKSPACE B. (Then add them as Viewer or Editor on a project under WORKSPACE B.)

There has to be a way to do this ( and with SSO in production as well)
